# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo5.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(526, 500)
        self.label_video = QtWidgets.QLabel(Form)
        self.label_video.setGeometry(QtCore.QRect(50, 10, 401, 311))
        self.label_video.setText("")
        self.label_video.setObjectName("label_video")
        self.pushButton_select = QtWidgets.QPushButton(Form)
        self.pushButton_select.setGeometry(QtCore.QRect(180, 370, 75, 23))
        self.pushButton_select.setObjectName("pushButton_select")
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setGeometry(QtCore.QRect(90, 370, 75, 23))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(10, 370, 75, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 330, 491, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(280, 370, 221, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_select.setText(_translate("Form", "选择文件"))
        self.pushButton_stop.setText(_translate("Form", "停止"))
        self.pushButton_start.setText(_translate("Form", "开始"))
        self.lineEdit.setText(_translate("Form", "video player interface"))
