# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avideo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1091, 750)
        Form.setStyleSheet("QWidget{\n"
"background-color:  rgb(213, 213, 213)}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_video = QtWidgets.QLabel(Form)
        self.label_video.setStyleSheet("QWidget{\n"
"background-color:rgb(0, 0, 0)\n"
"}")
        self.label_video.setObjectName("label_video")
        self.verticalLayout.addWidget(self.label_video)
        self.pushButton_select = QtWidgets.QPushButton(Form)
        self.pushButton_select.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255)} ")
        self.pushButton_select.setObjectName("pushButton_select")
        self.verticalLayout.addWidget(self.pushButton_select)
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setStyleSheet(" QWidget{\n"
"background-color: rgb(255, 255, 255)}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.verticalLayout.addWidget(self.pushButton_start)
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255)} ")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.verticalLayout.addWidget(self.pushButton_stop)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_video.setText(_translate("Form", "video"))
        self.pushButton_select.setText(_translate("Form", "select"))
        self.pushButton_start.setText(_translate("Form", "start"))
        self.pushButton_stop.setText(_translate("Form", "stop"))
